- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: test test.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review
